name: Java CI with Gradle

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - run: gradle run -DmainClass=com.google.swarm.tokenization.DLPTextToBigQueryStreamingV2 -Pargs=" --region=us-central1 --project=elite-striker-388810 --streaming --enableStreamingEngine --tempLocation=gs://elite-striker-388810-demo-data/temp --numWorkers=2 --maxNumWorkers=3 --runner=DataflowRunner --filePattern=gs://elite-striker-388810-demo-data/*.csv --dataset=demo_dataset  --inspectTemplateName=projects/elite-striker-388810/locations/global/inspectTemplates/dlp-demo-inspect-latest-1681984318592 --deidentifyTemplateName=projects/elite-striker-388810/locations/global/deidentifyTemplates/dlp-demo-deid-latest-1681984318592 --DLPMethod=DEID"
