name: Java CI with Gradle

on:
  push:
    branches:
      - ci_workflow

permissions: write-all

jobs:
  build:
    runs-on: 
      - self-hosted
      - gh-test-1

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - run: gradle run -DmainClass=com.google.swarm.tokenization.DLPTextToBigQueryStreamingV2 -Pargs=" --region=us-central1 --project=dlp-dataflow-deid-test --streaming --enableStreamingEngine --tempLocation=gs://dlp-dataflow-deid-test-demo-data/temp --numWorkers=2 --maxNumWorkers=3 --runner=DataflowRunner --filePattern=gs://dlp-dataflow-deid-test-demo-data/*.csv --dataset=demo_dataset  --inspectTemplateName=projects/dlp-dataflow-deid-test/locations/global/inspectTemplates/dlp-demo-inspect-latest-1686302920427 --deidentifyTemplateName=projects/dlp-dataflow-deid-test/locations/global/deidentifyTemplates/dlp-demo-deid-latest-1686302920427 --DLPMethod=DEID"
