name: Java CI with Gradle

on:
  push:
    branches:
      - ci_workflow

jobs:
  run-and-verify:
    runs-on: 
      - self-hosted
      - gh-test-2

    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Get Project ID
        run: echo $(gcloud config get-value project)
      
#       - name: Run DLP Pipeline
#         run: gradle run -DmainClass=com.google.swarm.tokenization.DLPTextToBigQueryStreamingV2 -Pargs=" --region=us-central1 --project=muskan-dlp-test-local3 --streaming --enableStreamingEngine --tempLocation=gs://muskan-dlp-test-local3-demo-data/temp --numWorkers=2 --maxNumWorkers=3 --runner=DataflowRunner --filePattern=gs://muskan-dlp-test-local3-demo-data/*.csv --dataset=gh_test_2  --inspectTemplateName=projects/muskan-dlp-test-local3/locations/global/inspectTemplates/dlp-demo-inspect-latest-1680688062701 --deidentifyTemplateName=projects/muskan-dlp-test-local3/locations/global/deidentifyTemplates/dlp-demo-deid-latest-1680688062701 --batchSize=200000 --DLPMethod=DEID"
      
      - name: Verify BQ tables
        run: |
          tables_verified=false
          table_count=0
          while !tables_verified; do
            table_count=$(($(bq query --use_legacy_sql=false --format csv 'SELECT * FROM `muskan-dlp-test-local3.gh_test_2`.__TABLES__'  | wc -l ) -1))
            if [[ $table_count == 5 ]]; then 
              echo "PASSED"; 
              tables_verified=true;
            else
              sleep 5m
            fi
          done
          echo "Verified number of tables in BQ: $table_count ."
      
      - name: Verify distinct rows
        run: |
          rows_verified=false
          row_count=0
          while !rows_verified; do
            row_count1=$(bq query --use_legacy_sql=false --format json 'SELECT COUNT(DISTINCT(ID)) FROM `muskan-dlp-test-local3.gh_test_2.CCRecords_1564602825`')
            row_count=$(echo "$row_count1" | jq -r '.[].f0_')
            if [[ $row_count == "99999" ]]; then 
              echo "PASSED"; 
              rows_verified=true;
            else
              sleep 5m
            fi
          done
          echo "Verified number of rows in CCRecords_1564602825: $row_count ."
