name: Java CI with Gradle

on:
  push:
    branches:
      - ci_workflow

jobs:
  run-and-verify:
    runs-on: 
      - self-hosted
      - gh-test-2

    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
#       - name: Run DLP Pipeline
#         run: gradle run -DmainClass=com.google.swarm.tokenization.DLPTextToBigQueryStreamingV2 -Pargs=" --region=us-central1 --project=muskan-dlp-test-local3 --streaming --enableStreamingEngine --tempLocation=gs://muskan-dlp-test-local3-demo-data/temp --numWorkers=2 --maxNumWorkers=3 --runner=DataflowRunner --filePattern=gs://muskan-dlp-test-local3-demo-data/*.csv --dataset=gh_test_2  --inspectTemplateName=projects/muskan-dlp-test-local3/locations/global/inspectTemplates/dlp-demo-inspect-latest-1680688062701 --deidentifyTemplateName=projects/muskan-dlp-test-local3/locations/global/deidentifyTemplates/dlp-demo-deid-latest-1680688062701 --batchSize=200000 --DLPMethod=DEID"
      
      - name: Verify BQ tables
        run: |
          table_count_orig=$(gsutil du gs://muskan-dlp-test-local3-demo-data/*.csv | wc -l)
          not_verified=true
          table_count=0
          while $not_verified; do
            table_count=$(($(bq query --use_legacy_sql=false --format csv 'SELECT * FROM `muskan-dlp-test-local3.gh_test_2`.__TABLES__'  | wc -l ) -1))
            if [[ "$table_count" == "5" ]]; then
              echo "PASSED"; 
              not_verified=false;
            else
              sleep 5m
            fi
          done
          echo "# CSV files in demo-data bucket is: $table_count_orig."
          echo "Verified number of tables in BQ: $table_count ."
      
      - name: Verify distinct rows
        run: |
          rc_orig1=$(($(gcloud storage cat gs://muskan-dlp-test-local3-demo-data/CCRecords_1564602825.csv | wc -l ) -1))
          rc_orig2=$(($(gcloud storage cat gs://muskan-dlp-test-local3-demo-data/CCRecords_1564602826.csv | wc -l ) -1))
          rc_orig3=$(($(gcloud storage cat gs://muskan-dlp-test-local3-demo-data/CCRecords_1564602828.csv | wc -l ) -1))
          rc_orig4=$(($(gcloud storage cat gs://muskan-dlp-test-local3-demo-data/CCRecords_1564602829.csv | wc -l ) -1))
          rc_orig5=$(($(gcloud storage cat gs://muskan-dlp-test-local3-demo-data/CCRecords_1564602830.csv | wc -l ) -1))
          not_verified=true
          rc1=0
          rc2=0
          rc3=0
          rc4=0
          rc5=0
          while $not_verified; do
            row_count=$(bq query --use_legacy_sql=false --format json 'SELECT COUNT(DISTINCT(ID)) FROM `muskan-dlp-test-local3.gh_test_2.CCRecords_1564602825`')
            rc1=$(echo "$row_count" | jq -r '.[].f0_')
            row_count=$(bq query --use_legacy_sql=false --format json 'SELECT COUNT(DISTINCT(ID)) FROM `muskan-dlp-test-local3.gh_test_2.CCRecords_1564602826`')
            rc2=$(echo "$row_count" | jq -r '.[].f0_')
            row_count=$(bq query --use_legacy_sql=false --format json 'SELECT COUNT(DISTINCT(ID)) FROM `muskan-dlp-test-local3.gh_test_2.CCRecords_1564602828`')
            rc3=$(echo "$row_count" | jq -r '.[].f0_')
            row_count=$(bq query --use_legacy_sql=false --format json 'SELECT COUNT(DISTINCT(ID)) FROM `muskan-dlp-test-local3.gh_test_2.CCRecords_1564602829`')
            rc4=$(echo "$row_count" | jq -r '.[].f0_')
            row_count=$(bq query --use_legacy_sql=false --format json 'SELECT COUNT(DISTINCT(ID)) FROM `muskan-dlp-test-local3.gh_test_2.CCRecords_1564602830`')
            rc5=$(echo "$row_count" | jq -r '.[].f0_')
            if [[ "$rc1" == "$rc_orig1" && "$rc2" == "$rc_orig2" && "$rc3" == "$rc_orig3" && "$rc4" == "$rc_orig4" && "$rc5" == "$rc_orig5" ]]; then 
              echo "PASSED"; 
              not_verified=false;
            else
              sleep 5m
            fi
          done
          echo "# records in input CSV files are: $rc_orig1, $rc_orig2, $rc_orig3, $rc_orig4, $rc_orig5."
          echo "Verified number of rows in CCRecords_1564602825: $rc1 , $rc2 , $rc3 , $rc4 , $rc5 ."
